/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppDetectiveRouteImport } from './routes/app.detective'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppInvestigationsRouteImport } from './routes/app.investigations'
import { Route as AppPlaygroundRouteImport } from './routes/app.playground'
import { Route as AppReplayRouteImport } from './routes/app.replay'
import { Route as AppSettingsRouteImport } from './routes/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectiveRoute = AppDetectiveRouteImport.update({
  id: '/detective',
  path: '/detective',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsRoute = AppInvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/compare': typeof AppCompareRoute
  '/app/detective': typeof AppDetectiveRoute
  '/app/health': typeof AppHealthRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/compare': typeof AppCompareRoute
  '/app/detective': typeof AppDetectiveRoute
  '/app/health': typeof AppHealthRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/compare': typeof AppCompareRoute
  '/app/detective': typeof AppDetectiveRoute
  '/app/health': typeof AppHealthRoute
  '/app/investigations': typeof AppInvestigationsRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/replay': typeof AppReplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/compare'
    | '/app/detective'
    | '/app/health'
    | '/app/investigations'
    | '/app/playground'
    | '/app/replay'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/compare'
    | '/app/detective'
    | '/app/health'
    | '/app/investigations'
    | '/app/playground'
    | '/app/replay'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/compare'
    | '/app/detective'
    | '/app/health'
    | '/app/investigations'
    | '/app/playground'
    | '/app/replay'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/detective': {
      id: '/app/detective'
      path: '/detective'
      fullPath: '/app/detective'
      preLoaderRoute: typeof AppDetectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investigations': {
      id: '/app/investigations'
      path: '/investigations'
      fullPath: '/app/investigations'
      preLoaderRoute: typeof AppInvestigationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playground': {
      id: '/app/playground'
      path: '/playground'
      fullPath: '/app/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/replay': {
      id: '/app/replay'
      path: '/replay'
      fullPath: '/app/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompareRoute: typeof AppCompareRoute
  AppDetectiveRoute: typeof AppDetectiveRoute
  AppHealthRoute: typeof AppHealthRoute
  AppInvestigationsRoute: typeof AppInvestigationsRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppReplayRoute: typeof AppReplayRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompareRoute: AppCompareRoute,
  AppDetectiveRoute: AppDetectiveRoute,
  AppHealthRoute: AppHealthRoute,
  AppInvestigationsRoute: AppInvestigationsRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppReplayRoute: AppReplayRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
