server {
  listen       3301;
  server_name  _;

  client_max_body_size 24M;
  large_client_header_buffers 8 128k;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /api {
    proxy_pass http://signoz-query-service:8080;
  }
}
